### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by gitfort47** [vakhariaheet/verifierjs#4]
**Is your feature request related to a problem? Please describe.**
Im always frustrated when setting up the system

**Describe the solution you'd like**
Setup Docker

**Describe alternatives you've considered**
Vagrant but its depreciated in minds of devs

**Comment by vakhariaheet** [comment]
Thanks Bro but my Feature request related to new Functions which can be added in this package and I am not that familiar with docker can u explain why would we need to docker in this package
